language: ruby

services:
  - docker
  

cache:
  bundler: true
  directories:
    - $HOME/docker
    
before_cache:
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
    
script:
  - docker -v
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker
  
