language: ruby

services:
  - docker
  

cache:
  bundler: true
  directories:
    - $HOME/docker
    
before_cache:
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
    
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  
script:
  - docker -v
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker buildx create --use --name mybuilder
  - docker buildx ls
  - echo "1255900858ecw.." | docker login -u "xiaodi93" --password-stdin
  - docker buildx build -t xiaodi93/ant-design:amd64 --platform=linux/amd64 . --push
  - docker buildx build -t xiaodi93/ant-design:latest --platform=linux/arm64 . --push
  
